### ISSUE TITLE
Can't install thermostate using pip and python 3.6

### ISSUE THREAD

**Issue by william-pfalzgraff** [bryanwweber/thermostate#13]
I'm not able to install thermostate using pip. In particular, when I try to install it I get this error message:

$ pip install thermostate
Collecting thermostate
  Downloading https://files.pythonhosted.org/packages/b0/2a/f19e8bd5556565ce12360e7bdde1765927e5d8a192137b94be5174daf6db/thermostate-0.4.2-py3-none-any.whl
Collecting coolprop<6.2,>=6.1.0 (from thermostate)
  Could not find a version that satisfies the requirement coolprop<6.2,>=6.1.0 (from thermostate) (from versions: 2.0.1, 2.0.2, 2.0.4, 2.0.5, 2.0.6, 2.1, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.3, 2.4, 2.5, 3.0.1, 3.1, 3.1.1, 3.1.2, 3.2.0, 3.3.0, 4.0.0b0, 4.0.0, 4.1.0, 4.1.1, 4.1.2, 4.2.0, 4.2.2, 4.2.3, 4.2.4, 4.2.5, 5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.0.4, 5.0.5, 5.0.6, 5.0.7, 5.0.8, 5.1.0, 5.1.1, 5.1.2, 6.0.0)
No matching distribution found for coolprop<6.2,>=6.1.0 (from thermostate)

It looks like there is an issue with the coolprop dependency.  (I am able to install coolprop using pip, but doing so does not resolve the problem). 

If helpful, I am running Anaconda python 3.6.

**Comment by bryanwweber** [comment]
@william-pfalzgraff You say
> I am able to install coolprop using pip, but doing so does not resolve the problem

Are you able to install CoolProp using pip into this Python 3.6 environment?

**Comment by william-pfalzgraff** [comment]
As far as I know I can install coolprop; my pip command and output for doing so is pasted below.

william-pfalzgraff$ pip install CoolProp
Collecting CoolProp
  Using cached https://files.pythonhosted.org/packages/e6/c8/a206a2cc3cb189b2b84c13e6fcea97a9faafacaa9866dd0e49b42f1b5608/CoolProp-6.0.0.tar.gz
Building wheels for collected packages: CoolProp
  Running setup.py bdist_wheel for CoolProp ... done
  Stored in directory: /Users/williampfalzgraff/Library/Caches/pip/wheels/07/ee/01/4566384c81e7a4d8f901550ea21fe711db8c29e9434aad151f
Successfully built CoolProp
Installing collected packages: CoolProp
Successfully installed CoolProp-6.0.0

After which, for example, "import CoolProp.CoolProp as CP" works fine in python 3.6.5

That said, it looks like I have version 6.0.0, not 6.1.0 as required by thermostate. Will 6.0.0 not work for you?  I do see that the wheels available on PyPI only go up to python 3.5 for CoolProp 6.1.0.

Regarding the issues, to my mind there are two threads of discussion that merit two separate issues.  One is the documentation, including adding installation instructions to the Readme.  The other is making sure that it can be installed using common package managers. If it can't be installed with pip then documenting that fact would be good.  That said, if 6.0.0 would work for you, then is it possible to get the pip install working? I do think making the project as available as possible would be very helpful.

My preference would be to open a separate issue for the ReadMe, but I'll defer to you on that.

**Comment by bryanwweber** [comment]
@william-pfalzgraff Sure, a separate issue would probably make sense to update the docs and README.

As for this issue, I don't know if 6.0.0 will work, I haven't tested it. In any case, the only reason it works is because there's a source distribution available, and you happen to be on a platform where `pip install` finds the C++ compiler necessary for the extension. So for folks on platforms where that's not the case (i.e., Windows), the `pip install` won't really work either. So my preference is just to require the most recent version, and deal with the limitations on pip-installing on Python versions. Do you agree with this line of reasoning?

**Comment by bryanwweber** [comment]
@william-pfalzgraff My preference is to not encourage people to install outdated versions of their software; there is at least one bug in CoolProp 6.1.0 that I know of (that has been fixed on the master branch) that just bit me on an exam problem 😄 So I'm sure there are other bugs that were fixed between 6.0.0 and 6.1.0. Nonetheless, I think its a good idea for my own understanding to see whether or not the test suite at least passes with 6.0.0, so I'll try that and perhaps make a note in the installation instructions.

**Comment by bryanwweber** [comment]
@william-pfalzgraff I checked this and the test suite passes with CoolProp 6.0.0. So I'll say it's officially unsupported, but it works if you need it.

**Comment by william-pfalzgraff** [comment]
Great, then I think it makes sense to consider this issue closed. Thanks!
