### ISSUE TITLE
Update README with installation instructions and links to documentation

### ISSUE THREAD

**Issue by william-pfalzgraff** [bryanwweber/thermostate#14]
The ideal, in my view, would be one clearly preferred set of installation instructions with sufficient detail so that potential users not familiar with CoolProp or Pint can install the package easily.  (I am such a potential user).  It seems that conda is the preferred way that is most likely to work?

The package is very well documented [here](https://bryanwweber.github.io/thermostate/) but it took me quite a while to find that out. It would be good to provide links to different parts of the documentation in the README so that an interested user viewing the repo can easily find the tutorial, examples, documentation, etc.

**Comment by bryanwweber** [comment]
@william-pfalzgraff Is the detail in d836c97 and 8707820 sufficient?

**Comment by william-pfalzgraff** [comment]
Looks great!
