### ISSUE TITLE
Build number in conda search no longer contains python version

### ISSUE THREAD

**Issue by mdbernard** [bryanwweber/thermostate#19]
When searching for thermostate using `conda search thermostate` in terminal, results after version 0.3.0, up to and including the current version 0.5.3, no longer have the python version in the build number.

Up to version 0.2.2, build numbers are similar to `py36_0`, with `36` the python version. Starting with version 0.3.0 onward, they are all "py_0". This makes it somewhat difficult to tell which version of python they'll work for.

Not sure if this is intentional, but it would be convenient if the compatible python version remained visible in the build number.

**Comment by bryanwweber** [comment]
Hi @mdbernard! This is because the code is not specific to a particular Python version, and the same package file will work for any Python version >=3.5. The option in the conda-build `meta.yaml` is called `noarch`. You can see the specific dependencies of a particular version with
```
conda search -c bryanwweber --info thermostate=0.5.3
```

**Comment by mdbernard** [comment]
Thanks!
