### ISSUE TITLE
Add plots from CoolProp

### ISSUE THREAD

**Issue by bryanwweber** [bryanwweber/thermostate#3]
See http://www.coolprop.org/coolprop/python-plotting.html http://www.coolprop.org/apidoc/CoolProp.Plots.Common.html#CoolProp.Plots.Common.BasePlot and http://www.coolprop.org/apidoc/CoolProp.Plots.Common.html#CoolProp.Plots.Common.Base2DObject

**Comment by ibell** [comment]
Hi @bryanwweber Since you are a thermo person and a python person (nice job with this project BTW!), any interest in fixing the plotting routines in CoolProp?  We've run out of person-power for fixing and updating the plotting routines in CoolProp...

**Comment by bryanwweber** [comment]
Hi @ibell! Thank you for the awesome CoolProp that makes this project possible 😄 I'd be happy to take a look, but I won't have time until the summer.
