### ISSUE TITLE
plotting issue [ thermostate.plotting]

### ISSUE THREAD

**Issue by m-suhermanto** [bryanwweber/thermostate#36]
### Code sample, preferably able to be copy-pasted and run with no changes
from thermostate import State, Q_, units
from thermostate.plotting import IdealGas, VaporDome

### Expected behavior
should not be an issue while importing
I have installed using 'pip install thermostate`

### Actual behavior, including any error messages
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-07997053a537> in <module>
      1 from thermostate import State, Q_, units
----> 2 from thermostate.plotting import IdealGas, VaporDome

ModuleNotFoundError: No module named 'thermostate.plotting'

### Thermostate version, Python version, OS version
thermostate 1.2.1
Python 3.8.8
OS Windows 10 64bit

**Comment by bryanwweber** [comment]
Hum, looks like I haven't cut a release yet with the plotting features! I'll try to take care of that soon and let you know. Thanks for reporting this!

Can I ask where and why you're using ThermoState?

**Comment by msuherma** [comment]
Dr. Weber,

Thank you for your time and swift response.

I am finishing my PhD in environmental engineering at Purdue Univ. However, I will be teaching thermodynamics for undergrad in a small university back home (Indonesia) after my graduation. As I recently been introduced to python, I see a lot of potential in it and start to grasp the thermo using python myself. Teaching Thermo without any programming is far from ideal, yet the EES price is unaffordable for the students in our university. I see your work focusing on more hands-on/practical approach to thermo for engineers and simplifying the usage of coolprop and pint. To my current understanding, that's all I need to deliver material coupled with Thermo-Engineering books such as Cengle-Boles' or Moran-Shapiro's.

Best,
Mo

**Comment by bryanwweber** [comment]
@msuherma Wow, very cool! Yes, I developed this package alongside teaching a course with Moran/Shapiro's book, so it is very well suited for that style of book. I'll publish a new release soon!

**Comment by msuherma** [comment]
Dr. @bryanwweber , I can't wait for the release of the teaching materials covering Moran-Shapiro's book. It will surely help me a lot. Perhaps, I will try to create the Cengel-Boles version in near future, referring to your Moran-Shapiro's work. Again, I am a very beginner in Python, but I understand its huge necessity in teaching-learning process; and I love teaching. Be looking forward to it. ~Mo

**Comment by bryanwweber** [comment]
Hi @msuherma Sorry, I don't have any more teaching materials to release. I do have a sequence of videos on YouTube that cover Chapters 1-13 in the Moran/Shapiro book.

I meant a release of this software package to include the plotting module! 😃

**Comment by bryanwweber** [comment]
Plotting was included in the 1.3.0 release.

**Comment by suhermantom** [comment]
Thank you very much, Dr. Weber. I appreciate your kindness and great work.

Best,
Mo

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
