### ISSUE TITLE
expand list of substances

### ISSUE THREAD

**Issue by iotium** [bryanwweber/thermostate#5]
CoolProp supports a long list of substances. Is there any reason thermostate can't support all of them? Currently it's limited to:

['AIR', 'AMMONIA', 'WATER', 'PROPANE', 'R134A', 'R22', 'ISOBUTANE',
                     'CARBONDIOXIDE', 'OXYGEN', 'NITROGEN']

Full list of coolprop-supported fluids: http://www.coolprop.org/fluid_properties/PurePseudoPure.html#list-of-fluids

**Comment by bryanwweber** [comment]
Hi! The main reason it's limited to these substances is these are the ones I use in my class, and I don't want my students to end up with the wrong substance or something weird. There's no technical reason that all of the substances can't be enabled.

If you don't mind my asking, you're the first person (other than me) who's shown interest in the software, and I'm curious how you intend to use ThermoState, and where. Thanks!

**Comment by bryanwweber** [comment]
No response in 5 years, closing
